package project;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Writer;
import java.net.ConnectException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import web.hyperspec.Hyperspec;
import web.hyperspec.Outcome;
import web.hyperspec.SpecException;

/// Runs hyperspecs from the filesystem against an application that is already
/// running.
///
/// `web.hyperspec` can already run a spec; what it cannot do is find one. A
/// spec that travels with the code that runs it is a resource, and a spec
/// somebody is writing right now is a file they just saved — this is the second
/// kind. `tuul hyperspec :8099 spec/browse/*.hyperspec` is the shell doing the
/// globbing and this doing the rest.
///
/// Three things go wrong here and they are not the same thing: a file that is
/// not there, a spec that does not parse, and a host with nothing behind it.
/// The first two are mistakes in what was asked for and are refused before
/// anything runs; the third is refused before the first request, because twelve
/// specs failing on `Connection refused` is a worse way to learn it than one
/// sentence.
public final class Specs {

    /// How long to wait to find out whether anything is listening. Long enough
    /// for a server still starting up, short enough that a wrong port is a
    /// pause rather than a hang.
    private static final Duration PATIENCE = Duration.ofSeconds(5);

    /// A spec to run and what to call it in the report — a file's path, `-` for
    /// standard input, `--eval` for one given on the command line.
    public record Source(String name, String text) {}

    /// How many specs ran and how many did not hold.
    public record Result(int ran, int failed) {}

    private Specs() {}

    /// Where the application is, from what somebody typed.
    ///
    /// `http://localhost:8099`, `localhost:8099` and `:8099` all mean the same
    /// thing and all get typed; the last is the one worth having, because the
    /// common case is a server on this machine and a port is the only part of
    /// that anybody remembers. A bare number is refused rather than guessed at:
    /// `8099` is a hostname as far as a URI is concerned, and a tool that
    /// quietly turns it into a port is a tool that will one day quietly turn a
    /// hostname into one.
    public static URI host(String given) {
        var text = given.strip();
        if (text.isEmpty()) throw new IllegalArgumentException("a host is needed: try :8099 or http://localhost:8099");
        if (text.chars().allMatch(Character::isDigit)) {
            throw new IllegalArgumentException("a host needs a name or a colon: " + text
                    + " looks like a port, so try :" + text);
        }

        var uri = parse(text.contains("://") ? text : "http://" + (text.startsWith(":") ? "localhost" + text : text));
        if (!"http".equals(uri.getScheme()) && !"https".equals(uri.getScheme())) {
            throw new IllegalArgumentException("a host is reached over http or https, not " + uri.getScheme());
        }
        if (uri.getHost() == null) throw new IllegalArgumentException("no host in " + given);
        if (uri.getPath() != null && !uri.getPath().isEmpty() && !uri.getPath().equals("/")) {
            throw new IllegalArgumentException("a host is where the application is listening, not a path inside it: "
                    + "try " + uri.getScheme() + "://" + uri.getRawAuthority() + " and let the spec say " + uri.getPath());
        }
        return uri;
    }

    private static URI parse(String text) {
        try {
            return new URI(text);
        } catch (URISyntaxException e) {
            throw new IllegalArgumentException("not a host: " + text);
        }
    }

    /// The specs named on a command line, in the order they were named.
    ///
    /// `-` is standard input, as it is everywhere else, so a spec generated by
    /// something else can be piped in without being written down first. A file
    /// that is not there stops everything before the first request: a run that
    /// silently skips what it was asked for is worse than one that refuses.
    public static List<Source> files(List<String> paths) throws IOException {
        var sources = new ArrayList<Source>();
        for (var path : paths) {
            sources.add(path.equals("-") ? stdin() : file(Path.of(path)));
        }
        return List.copyOf(sources);
    }

    private static Source file(Path path) throws IOException {
        if (!Files.isRegularFile(path)) throw new IOException("no such spec: " + path);
        return new Source(path.toString(), Files.readString(path, StandardCharsets.UTF_8));
    }

    private static Source stdin() throws IOException {
        try (var in = new BufferedReader(new InputStreamReader(System.in, StandardCharsets.UTF_8))) {
            return new Source("-", in.lines().reduce("", (all, line) -> all + line + "\n"));
        }
    }

    /// Runs every spec against the service, reporting each as it finishes.
    ///
    /// The report is written as it goes rather than at the end, because a suite
    /// against a live server takes as long as the server does and a person
    /// watching one wants to know which spec is slow.
    public static Result run(URI service, List<Source> sources, boolean quiet, Writer out) throws IOException {
        if (sources.isEmpty()) throw new IOException("nothing to run: name a spec file, or give --eval a spec");
        reachable(service);

        var failed = 0;
        for (var source : sources) {
            if (!report(source, service, quiet, out)) failed++;
        }
        out.flush();
        return new Result(sources.size(), failed);
    }

    /// One spec, in the shape `mise run spec` prints — the same two-space
    /// indent and the same words, because somebody reading both should not have
    /// to learn two formats.
    private static boolean report(Source source, URI service, boolean quiet, Writer out) throws IOException {
        Outcome outcome;
        try {
            outcome = Hyperspec.run(source.text(), service);
        } catch (SpecException unreadable) {
            out.write(source.name() + "\n  FAIL " + unreadable.getMessage() + "\n  unreadable\n\n");
            return false;
        }

        if (!quiet || !outcome.ok()) out.write(source.name() + "\n");
        if (!quiet) {
            for (var check : outcome.checks()) out.write("  ok   " + check.client() + " " + check.what() + "\n");
        }
        for (var failure : outcome.failures()) out.write("  FAIL " + failure.describe() + "\n");
        if (!quiet || !outcome.ok()) {
            out.write("  " + outcome.passed() + " met"
                    + (outcome.ok() ? "" : ", " + outcome.failures().size() + " not") + "\n\n");
        }
        return outcome.ok();
    }

    /// Whether anything is behind the host at all.
    ///
    /// Any answer will do, including a 404: this asks whether the port is
    /// open, not whether the application is the right one. Only a refused
    /// connection is worth stopping for, and it is worth stopping for because
    /// every spec would otherwise fail the same way and say the same thing
    /// twelve times.
    private static void reachable(URI service) throws IOException {
        try (var client = HttpClient.newBuilder().connectTimeout(PATIENCE).build()) {
            client.send(HttpRequest.newBuilder(service).timeout(PATIENCE)
                    .method("HEAD", HttpRequest.BodyPublishers.noBody()).build(),
                    HttpResponse.BodyHandlers.discarding());
        } catch (ConnectException refused) {
            throw new IOException("nothing is listening at " + service);
        } catch (IOException unreachable) {
            throw new IOException("cannot reach " + service + ": " + unreachable.getMessage());
        } catch (InterruptedException interrupted) {
            Thread.currentThread().interrupt();
            throw new IOException("interrupted while reaching " + service);
        }
    }
}
